# Generated by Django 6.1.2 on 2026-10-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='height',
            field=models.FloatField(default=140),
        ),
        migrations.AddField(
            model_name='idea',
            name='width',
            field=models.FloatField(default=220),
        ),
    ]
