# Generated by Django 6.1.2 on 2026-10-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_board_idea_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='board',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
